# Generated by Django 5.2.6 on 2026-01-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField(help_text='pesos')),
                ('tipo', models.TextField()),
                ('valoracion', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
